### ISSUE TITLE
SSL certificate expired for demo server

### ISSUE THREAD

**Issue by dector** [Kinto/kinto-website#18]
__Assumptions__:
`httpie` is installed in the system.

__Steps to reproduce__:

1. Open tutorial on [First steps](http://kinto.readthedocs.io/en/latest/tutorials/first-steps.html#basic-data-storage-apis) page.
2. Execute first code snippet in terminal emulator:
``` bash
$ echo '{"data": {"description": "Write a tutorial explaining Kinto", "status": "todo"}}' | \
    http POST https://kinto.dev.mozaws.net/v1/buckets/default/collections/tasks/records \
         -v --auth 'token:my-secret'
```

__Expected result__:
httpie proceed request and displayed request and response information to terminal.

__Actual result__:
```
http: error: SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",) while doing POST request to URL: https://kinto.dev.mozaws.net/v1/buckets/default/collections/tasks/records
```

__Reason__:
SSL certificate on https://kinto.dev.mozaws.net/v1/ expired few days ago.

__Possible workaround__:
Execute `httpie` request with `--verify no` argument to skip SSL verification.

**Comment by leplatrem** [comment]
Thanks for reporting!

This seems to have been fixed in the mean time ;)
