### ISSUE TITLE
Website is down - not resolving

### ISSUE THREAD

**Issue by wesinator** [Kinto/kinto-website#20]
FYI, www.kinto-storage.org and none of the subdomains are resolving right now.

**Comment by glasserc** [comment]
Hi, thanks for the report. I know @mostlygeek is working on getting slack.kinto-storage.org back up and running. I didn't know about `www`. I guess we should put that on the list too.

**Comment by Natim** [comment]
@glasserc do you think it would be possible to configure the DNS to the Alwaysdata one, so that we could use the kinto-storage org there to modify the DNS?

    dns1.alwaysdata.com et dns2.alwaysdata.com.

**Comment by mostlygeek** [comment]
```
$ dig kinto-storage.org ns

; <<>> DiG 9.10.6 <<>> kinto-storage.org ns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4307
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kinto-storage.org.             IN      NS

;; ANSWER SECTION:
kinto-storage.org.      3492    IN      NS      dns1.alwaysdata.com.
kinto-storage.org.      3492    IN      NS      dns2.alwaysdata.com.
```

Is this good enough?

**Comment by Natim** [comment]
Apparently it is not good enough, it seems that you only changed the NS record of domain rather than the default DNS of the domain.

https://www.dnswatch.info/dns/dnslookup?la=en&host=kinto-storage.org&type=A&submit=Resolve

**Comment by Natim** [comment]
Here seems to be the procedure for AWS: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-name-servers-glue-records.html#domain-name-servers-glue-records-procedure

**Comment by Natim** [comment]
It seems to be working now, thanks: https://www.kinto-storage.org/
