### ISSUE TITLE
Dead link: encryption example

### ISSUE THREAD

**Issue by TeNNoX** [Kinto/kinto-website#25]
The link for encryption is dead:
![Screenshot from 2021-02-19 16-53-01](https://user-images.githubusercontent.com/2084639/108527764-f429a280-72d2-11eb-94b3-e381ee6018a3.png)

http://servicedenuages.fr/en/kinto-encryption-example
![image](https://user-images.githubusercontent.com/2084639/108527709-e3792c80-72d2-11eb-88b3-3dfee7d63b3b.png)

**Comment by Natim** [comment]
Please find it there: https://mozilla-services.github.io/servicedenuages.fr/en/kinto-encryption-example

**Comment by Natim** [comment]
Fixed with 85e0fda and thank you for filling an issue about it :pray:
