### ISSUE TITLE
Add a blog

### ISSUE THREAD

**Issue by enguerran** [Kinto/kinto-website#8]
As discussed in [the monthly meeting on september, 6th](https://pad.notmyidea.org/p/kinto-monthly), we would like to have a blog within the website.

We choose pelican as [the static blogging platform](https://github.com/getpelican/pelican/) and I will try to [automatized the build process with travis](http://blog.mathieu-leplatre.info/publish-your-pelican-blog-on-github-pages-via-travis-ci.html).

This issue will centralize problems, nice-to-have features, etc. 

I will open a Pull Request as soon as I have something to show you.
- [x] Menu: I can see the source code, but I cannot see the elements in the website: https://github.com/Kinto/kinto-website/blob/gh-pages/index.html#L48. Is someone could help on this one? Does it have to stay in the `index.html` or will it be removed? **there was a typo in the header menu `nav-left` → `navbar-left`**
- [ ] Menu: Where does the `contact` link should point to?
- [ ] Blog with Pelican: what is the difference between servicedesnuages.fr and kinto blog? In terms of content? In terms of structure? What if we fork servicedesnuages repository to create the kinto-website-with-a-blog?
- [ ] Website with Pelican: could we migrate all actual pages to pelican pages to use only one engine to build everything?

**Comment by Natim** [comment]
What would be the benefit of using Lektor? To have a WYSIWYG editor?

**Comment by enguerran** [comment]
It's written in python, it is modern and has learned from jekyll and pelican.
I think it is as good as pelican and whatever we choose, contents are written in markdown (just forget about reStructuredText who loses the battle like RTF does) and except for local img url, we could switch from one to another blog management system.

What do you think?

**Comment by enguerran** [comment]
Oh wait! In fact the new kinto-storage.org is built on pelican! Ok, so it is nonsense to adopt another engine.

**Comment by almet** [comment]
Hey. I've migrated the current website to pelican last week, yes!

Why not using lektor or something else, but my experience with it has been a bit complicated when I last tried. Though, I'm of course partial here. I believe using pelican allows us to act quickly, especially given the fact that it's well known, well documented and that… I know it very well.

Using any other system will mean learning how to use it, making mistakes and taking time to fix them. While this is an acceptable approach in general, I feel that our goal here is not the exploration of static engines but rather having something that works, and I believe that's already the case.

That being said, If anyone wants to do an experiment with lektor, hugo, jekyl, nikola or any other system, feel free to do so and post a pull request where we can compare the different solutions, but in my opinion our time would be better invested writing articles or coding on kinto itself.

**Comment by almet** [comment]
I'm closing this issue as the blog now exist. Feel free to open another discussion if you feel it's needed.

**Comment by DirtyF** [comment]
@almet Sorry I'm little confused here the blog icon links to http://www.servicedenuages.fr/en/ on http://www.kinto-storage.org/. 

We have an english post we would like to publish on Kinto's blog, where should we commit?

**Comment by almet** [comment]
This link needs to be updated :-) You need to just create a new file on this very repository, in the "content" folder, eventually using a subfolder which will act as a category (i.e. "app-examples") for the format, you can follow what's described in the pelican docs for markdown (see http://pelican.readthedocs.io/en/3.6.3/content.html)

**Comment by almet** [comment]
I've updated the link to the blogpost: https://github.com/Kinto/kinto-website/commit/82553c6a355345d7a618fda21f7316ce96cedce2
